import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { Manrope } from "next/font/google"; // Import Manrope font
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { CartProvider } from "@/context/cart-context";

// Import Manrope font and define the variable
const manrope = Manrope({
  variable: "--font-manrope", // Custom CSS variable for the font
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Millet Space",
  description: "Generated by create next app",
  icons: {
    icon: "/", // Favicon defined in metadata directly
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.variable} antialiased`}> {/* Use Manrope font here */}
          <CartProvider>
            <Navbar />
            {children}
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
