import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { Manrope } from "next/font/google"; // Import Manrope font
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { CartProvider } from "@/context/cart-context";
import Footer from "@/components/layout/Footer";

// Import Manrope font and define the variable
const manrope = Manrope({
  variable: "--font-manrope", // Custom CSS variable for the font
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Millet Space",
  description: "Generated by create next app",
  icons: {
    icon: "/", // Favicon defined in metadata directly
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <head>
        {/* Favicon Links */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
        <body className={`${manrope.variable} antialiased`}> {/* Use Manrope font here */}
          <CartProvider>
            <Navbar />
            {children}
            <Footer/>
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
